### ISSUE TITLE
[Bug]: Unable to download node

### ISSUE THREAD

**Issue by CocoPuffLeo** [huchenlei/ComfyUI-layerdiffuse#112]
### What happened?

Can't download it in comfyui.

### Steps to reproduce the problem

1. Open comfyui
2. download node
3. can't download.

### What should have happened?

should've download it.
![dffgbfhcgfj](https://github.com/user-attachments/assets/298b97a9-6018-4b2b-9e7c-985373a6ab40)

### Commit where the problem happens

ComfyUI:
ComfyUI-layerdiffuse:

### Sysinfo

I7-12700
3070RTX

### Console logs

```Shell
To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\Users\LeoWang\Downloads\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: C:\Users\LeoWang\Downloads\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
Install custom node 'ComfyUI-layerdiffuse (layerdiffusion)'
Try fixing: ['https://github.com/huchenlei/ComfyUI-layerdiffuse']
Install: pip packages
Attempt to fixing '['https://github.com/huchenlei/ComfyUI-layerdiffuse']' is done.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Install: ['https://github.com/huchenlei/ComfyUI-layerdiffuse.git']
Download: git clone 'https://github.com/huchenlei/ComfyUI-layerdiffuse.git'
[!]
0it [00:00, ?it/s]Cmd('git') failed due to: exit code(128)
0it [00:00, ?it/s]  cmdline: git clone -v --recursive --progress -- https://github.com/huchenlei/ComfyUI-layerdiffuse.git C:\Users\LeoWang\Downloads\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
```

### Workflow json file

[layer_diffusion_fg_example_rgba.json](https://github.com/user-attachments/files/17473789/layer_diffusion_fg_example_rgba.json)

**Comment by huchenlei** [comment]
This seems to be a network issue. Please confirm that you have VPN access if you are in China.
