### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by yamatazen** [huchenlei/ComfyUI-layerdiffuse#24]
This is the message on the console.

Traceback (most recent call last):
  File "C:\Users\yamat\Desktop\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\layered_diffusion.py", line 13, in <module>
    from .lib_layerdiffusion.utils import (
  File "C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\utils.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-layerdiffusion module for custom nodes: No module named 'cv2'
### ComfyUI Revision: 2036 [1abf8374] | Released on '2024-03-02'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-layerdiffusion
   0.0 seconds: C:\Users\yamat\Desktop\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.2 seconds: C:\Users\yamat\Desktop\ComfyUI\custom_nodes\ComfyUI-Manager

**Comment by huchenlei** [comment]
If you don't have opencv installed. You can install it by running `pip install opencv-python`. I have added opencv-python to requirements.txt.
