### ISSUE TITLE
Layer Diffusion Decode - unexpected keyword argument 'attn_groups'

### ISSUE THREAD

**Issue by dummerfranz** [huchenlei/ComfyUI-layerdiffuse#26]
> ERROR:root:Traceback (most recent call last):
  File "D:\comfyui_new\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui_new\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui_new\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui_new\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\layered_diffusion.py", line 112, in decode
    self.vae_transparent_decoder = TransparentVAEDecoder(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui_new\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\models.py", line 242, in __init__
    model = UNet1024(in_channels=3, out_channels=4)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui_new\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "D:\comfyui_new\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\models.py", line 131, in __init__
    self.mid_block = UNetMidBlock2D(
                     ^^^^^^^^^^^^^^^
TypeError: UNetMidBlock2D.__init__() got an unexpected keyword argument 'attn_groups'

ComfyUI-startup

> Total VRAM 8192 MB, total RAM 32653 MB
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
> VAE dtype: torch.bfloat16
> Using pytorch cross attention
> ComfyUI Revision: 2046 [a38b9b3a] | Released on '2024-03-04'

"Layer Diffuse Apply" Node is working as expected.

**Comment by huchenlei** [comment]
This is caused by diffusers version. Please follow the installation guide on install the correct version of diffusers.
