### ISSUE TITLE
Layer Diffuse Decode,The mask does not meet the expectations of the VAE Encode (for Inpainting) node

### ISSUE THREAD

**Issue by hben35096** [huchenlei/ComfyUI-layerdiffuse#28]
This should be a minor issue.
An error occurs when using the Layer Diffuse Decode node to output a mask to the VAE Encode (for Inpainting) node.

```
Error occurred when executing VAEEncodeForInpaint:

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/workspace/ComfyUI/nodes.py", line 364, in encode
pixels[:,:,:,i] *= m
```
![PixPin_2024-03-06_04-25-41](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/139383150/2cc79d46-b309-4b47-8953-41b7209a504c)

If download the mask image generated by the Layer Diffuse Decode node, upload it, and convert it into a mask, you can use the mask normally.

![PixPin_2024-03-06_04-28-45](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/139383150/71ef261b-ab24-49cc-9934-bc34bf94b027)

**Comment by hben35096** [comment]
/mnt/workspace/ComfyUI
** ComfyUI startup time: 2024-03-06 04:39:54.224686
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /opt/conda/bin/python
** Log path: /mnt/workspace/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 22732 MB, total RAM 30149 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/mnt/workspace/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

	"Don't let yesterday take up too much of today." - Will Rogers

[comfyui_controlnet_aux] | INFO -> Using ckpts path: /mnt/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
/mnt/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
### Loading: ComfyUI-Manager (V2.9)
### ComfyUI Revision: 2041 [0490ce82] | Released on '2024-03-04'
[ReActor] - STATUS - Running v0.4.1-b11 in ComfyUI
Torch version: 2.1.2+cu121
### Loading: ComfyUI-Impact-Pack (V4.80)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.

Import times for custom nodes:
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI_ben
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-AnimateDiff
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/comfyui-reactor-node
   0.0 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI_InstantID
   0.3 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-layerdiffuse
   1.2 seconds: /mnt/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux
   1.3 seconds: /mnt/workspace/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.3 seconds: /mnt/workspace/ComfyUI/custom_nodes/ComfyUI-YoloWorld-EfficientSAM

Starting server

To see the GUI go to: [http://127.0.0.1:8188](https://dsw-gateway-cn-shenzhen.data.aliyun.com/dsw-52631/proxy/8188/)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Client protocols [''] don’t overlap server-known ones ()
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
got prompt
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
left over keys: dict_keys(['conditioner.embedders.0.logit_scale', 'conditioner.embedders.0.text_projection'])
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|█████████████████████████████████████████████| 4/4 [00:02<00:00,  1.65it/s]
Requested to load AutoencoderKL
Loading 1 new model
100%|█████████████████████████████████████████████| 8/8 [00:01<00:00,  4.99it/s]
100%|█████████████████████████████████████████████| 8/8 [00:01<00:00,  5.41it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/nodes.py", line 364, in encode
    pixels[:,:,:,i] *= m
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by hben35096** [comment]
Thank you for everything :D
