### ISSUE TITLE
[Bug]: error executing Layer Diffuse Encode

### ISSUE THREAD

**Issue by krc1983** [huchenlei/ComfyUI-layerdiffuse#41]
### What happened?

The node simply doesn´t work, my workflow is quite simple (vide images), anyone? thanks.
![Captura de tela 2024-03-08 004514](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/4406740/ba2b6f61-63d2-4c11-aa95-54e93d21370a)
![Untitled](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/4406740/1cbd9aa3-3875-4beb-b415-f9e64f05b161)

### Steps to reproduce the problem

1. Execute the provided workflow.

### What should have happened?

Layer Diffuse Encode should produce an image and a mask.

### Commit where the problem happens

ComfyUI: I don´t know.
ComfyUI-layerdiffuse: I don´t know.

### Sysinfo

RTX 3060, WINDOWS 11

### Console logs

```Shell
Requested to load SDXL
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:25<00:00,  2.12s/it]
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:18<00:00,  2.26s/it]
Requested to load AutoencoderKL
Loading 1 new model
2024-03-08 01:00:16,298 - root - ERROR - !!! Exception during processing !!!
2024-03-08 01:00:16,530 - root - ERROR - Traceback (most recent call last):
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 299, in map_node_over_list
    return _map_node_over_list(obj, input_data_all, func, allow_interrupt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\layered_diffusion.py", line 109, in decode
    FUNCTION = "decode"

  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\models.py", line 242, in __init__
    model.load_state_dict(sd, strict=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "D:\AI_STUFF\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\models.py", line 131, in __init__
    in_channels=block_out_channels[-1],
                 ^^^^^^^^^^^^^^^^^^^^^^
TypeError: UNetMidBlock2D.__init__() got an unexpected keyword argument 'attn_groups'

Prompt executed in 67.34 seconds
2024-03-08 01:00:16,771 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1329' coro=<RequestHandler.start() done, defined at D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py:481> exception=AssertionError()>
Traceback (most recent call last):
  File "D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 485, in _make_request
    return _cls(
           ^^^^^
  File "D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_request.py", line 825, in __init__
    super().__init__(*args, **kwargs)
  File "D:\AI_STUFF\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_request.py", line 195, in __init__
    assert transport is not None
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Workflow json file

[LAYER_DIFF_WORKFLOW (1).json](https://github.com/huchenlei/ComfyUI-layerdiffuse/files/14532995/LAYER_DIFF_WORKFLOW.1.json)

**Comment by huchenlei** [comment]
Make sure you have valid diffusers version.

`diffusers>=0.25.0`

**Comment by huchenlei** [comment]
Diffuser version check added in https://github.com/huchenlei/ComfyUI-layerdiffuse/commit/2767a5b0f4e9d8bbbca6758e891aedb8e34d28ab

**Comment by krc1983** [comment]
> Make sure you have valid diffusers version.
> 
> `diffusers>=0.25.0`

Any light on how could I do that? I have no idea. I´d appreciate very much, thanks. 
P.S. Which diffuser should I look for again? thx.
