### ISSUE TITLE
can't load the node.. please help..

### ISSUE THREAD

**Issue by max140x** [huchenlei/ComfyUI-layerdiffuse#43]
![Screenshot 2024-03-08 173604](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/153641803/3fac2099-8ae2-4fb7-a1e0-5693571c8cdb)

**Comment by MokkaBoss1** [comment]
I have this issue too. In the console it says 

Traceback (most recent call last):
  File "F:\comfynew\ComfyUI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main\__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main\layered_diffusion.py", line 17, in <module>
    from .lib_layerdiffusion.models import TransparentVAEDecoder
  File "F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main\lib_layerdiffusion\models.py", line 22, in <module>
    check_diffusers_version()
  File "F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main\lib_layerdiffusion\models.py", line 17, in check_diffusers_version
    assert parse(diffusers.__version__) >= parse(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: diffusers>=0.25.0 requirement not satisfied. Please install correct diffusers version.

Cannot import F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main module for custom nodes: diffusers>=0.25.0 requirement not satisfied. Please install correct diffusers version.
### Loading: ComfyUI-Manager (V2.9)
### ComfyUI Revision: 2052 [55f37baa] | Released on '2024-03-07'

Import times for custom nodes:
   0.5 seconds: F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   6.2 seconds (IMPORT FAILED): F:\comfynew\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse-main

you might think reading this that I have the wrong version of diffusers but I checked and I have 0.25.0

**Comment by yotraxxx** [comment]
Exactly same issue here :-/

**Comment by HotHams** [comment]
Also having this issue. Any suggestions?

**Comment by Xiahussheng** [comment]
Exactly same issue here :-/

**Comment by polarsky89** [comment]
Make sure you update comfy's python packages, not the system python packages. Don't use PowerShell, just go with cmd

**Comment by MokkaBoss1** [comment]
by chance do you mean to do this:

pip install --upgrade pip
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U

**Comment by polarsky89** [comment]
That's the way to upgrade system python. In cmd (not powershell) go to python_embedded folder in your comfy standalone install folder, and start with python.exe
like this:
ComfyUI_windows_portable\python_embeded>python.exe pip and do your thing. You can also check the installed versions by using pip show <packgage name>

**Comment by MokkaBoss1** [comment]
just a thought would not executing the update bat file do the same?

update_comfyui_and_python_dependencies.bat - it is stored in the ComfyUi update folder

thanks

**Comment by yotraxxx** [comment]
Issue solved on my side by call a "pip install diffusers" with comfyui Manager/Install PIP Packages menu !

**Comment by MokkaBoss1** [comment]
ok great! Have you published the update?

**Comment by Xiahussheng** [comment]
> Issue solved on my side by call a "pip install diffusers" with comfyui Manager/Install PIP Packages menu !通过使用 comfyui Manager/Install PIP Packages 菜单调用“pip install diffusers”，我这边解决了问题！

it works！

**Comment by MokkaBoss1** [comment]
yes works for me too now.  For others looking here I went to the comfyui manager and in the experimental section (bottom left) I selected the option "Install PIP Packages". Then in the popup I entered "Diffusers" and then restarted comfyUI. I then tried to reinstall the custom node and it loaded without errors.

Thanks for the help.

**Comment by max140x** [comment]
> Issue solved on my side by call a "pip install diffusers" with comfyui Manager/Install PIP Packages menu !

thanksssssssssssssssssssssssssssss it's work for me

**Comment by max140x** [comment]
> yes works for me too now. For others looking here I went to the comfyui manager and in the experimental section (bottom left) I selected the option "Install PIP Packages". Then in the popup I entered "Diffusers" and then restarted comfyUI. I then tried to reinstall the custom node and it loaded without errors.
> 
> Thanks for the help.

i do than but without reinstall the node just restart comfyUi and it's work thanks bro

**Comment by MokkaBoss1** [comment]
Glad you made it work!

**Comment by HotHams** [comment]
Thank you so much, everyone. Got it working on my end thanks to this thread!
