### ISSUE TITLE
[Bug]: Fail to import

### ISSUE THREAD

**Issue by vicentecarro** [huchenlei/ComfyUI-layerdiffuse#57]
### What happened?

The node was working before but probably after thelast update it started failing to import.
This is the output
Setting temp directory to: /media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/c:/home/vicente/.temp/temp
Traceback (most recent call last):
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/layered_diffusion.py", line 23, in <module>
    from .lib_layerdiffusion.models import TransparentVAEDecoder
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/lib_layerdiffusion/models.py", line 8, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/huggingface_hub/constants.py)

Cannot import /media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/huggingface_hub/constants.py)

### Steps to reproduce the problem

simply launch comfyui and you can see in the output it failed to import.
Ma machine is linux (ubuntu 23.10)

### What should have happened?

it should have loaded fine as before.

### Commit where the problem happens

ComfyUI:
ComfyUI-layerdiffuse:

### Sysinfo

Linux Ubuntu 23.10, Graphic Card Nvidia RTX 3050 8GB

### Console logs

```Shell
Setting temp directory to: /media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/c:/home/vicente/.temp/temp
Traceback (most recent call last):
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/layered_diffusion.py", line 23, in <module>
    from .lib_layerdiffusion.models import TransparentVAEDecoder
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion/lib_layerdiffusion/models.py", line 8, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/huggingface_hub/constants.py)

Cannot import /media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-layerdiffusion module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/huggingface_hub/constants.py)
```

### Workflow json file

no json file required

**Comment by huchenlei** [comment]
I think this is a diffusers issue. You can file an issue in diffusers repo instead.
