### ISSUE TITLE
No module named 'diffusers.models.unet_2d_blocks'

### ISSUE THREAD

**Issue by 158zd** [huchenlei/ComfyUI-layerdiffuse#86]
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\stable-diffusion-webui\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ai\stable-diffusion-webui\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 23, in <module>
    from .lib_layerdiffusion.models import TransparentVAEDecoder
  File "D:\ai\stable-diffusion-webui\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\models.py", line 10, in <module>
    from diffusers.models.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_blocks'
![image](https://github.com/huchenlei/ComfyUI-layerdiffuse/assets/162105571/49c1edee-a898-4cfa-9f38-47a2382a72ba)
Same issue after installing diffusers

**Comment by AkihaTatsu** [comment]
Diffusers package has moved unet_2d_blocks.py into the "diffusers/models/unets/" path instead of the former "diffusers/models/" path. Line 10 in "lib_layerdiffusion/models.py" should be changed from `from diffusers.models.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block` to `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D, get_down_block, get_up_block`.
